import js from '@eslint/js'
import { globalIgnores } from 'eslint/config'
import eslintConfigPrettier from 'eslint-config-prettier'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import globals from 'globals'
import tseslint from 'typescript-eslint'

export default tseslint.config(
  // src/generated is tygo output from the Go wire contract (internal/scene),
  // regenerated by `task codegen` — not hand-written, so not linted.
  globalIgnores(['dist', 'coverage', 'e2e-results', 'playwright-report', 'src/generated']),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      ...tseslint.configs.recommended,
      reactHooks.configs.flat['recommended-latest'],
      reactRefresh.configs.vite,
      eslintConfigPrettier,
    ],
    languageOptions: {
      ecmaVersion: 2023,
      globals: globals.browser,
    },
  },
  {
    // Playwright config + e2e tests run in Node (the test runner), not the app
    // bundle: they need Node globals, and the react-refresh/component-export
    // conventions that guard the frontend don't apply. Their in-browser
    // page.evaluate callbacks still reference browser globals, so allow both.
    files: ['playwright.config.ts', 'e2e/**/*.ts'],
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
    },
    rules: {
      'react-refresh/only-export-components': 'off',
    },
  },
)
